[tool.black]
line-length = 88
target-version = ['py312']  # current Python version
skip-string-normalization = false
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | env
  | venv
  | migrations
  | build
  | dist
  | migrations
  | __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
lines_after_imports = 2
known_first_party = ["studio"]  # Django apps 
known_third_party = ["django", "rest_framework"]
skip = [".venv", "venv", "migrations", "__pycache__"]